### PR TITLE
Fix URL

### PR DESCRIPTION
**Pull request by swsnr**
😎

### CODE REVIEW

**Comment by halbtuerke** [comment]
Actually it's: https://github.com/halbtuerke/encourage-mode.el 😱😆

**Comment by swsnr** [comment]
Damn :(

**Comment by halbtuerke** [comment]
You could have just rebased and force-pushed instead of opening a new pull-request. :wink:

**Comment by swsnr** [comment]
@halbtuerke Not in Github's web-interface :wink:

**Pull request closed without merging**
